// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIeIe8RtQPUedJKcMWqdFAhjI1Vcz_KKM',
    appId: '1:358242017074:web:62514ad3068c599230012b',
    messagingSenderId: '358242017074',
    projectId: 'you-can-cook-1b811',
    authDomain: 'you-can-cook-1b811.firebaseapp.com',
    databaseURL: 'https://you-can-cook-1b811-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'you-can-cook-1b811.firebasestorage.app',
    measurementId: 'G-MG8PJ462BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw3SX9mZnut9NK6Q28dsoWoB9cFdNMwxQ',
    appId: '1:358242017074:android:762cc4f00c6e314c30012b',
    messagingSenderId: '358242017074',
    projectId: 'you-can-cook-1b811',
    databaseURL: 'https://you-can-cook-1b811-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'you-can-cook-1b811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDECLt-pA1IfCfoNi_jCfjNBP_-8ru0fHQ',
    appId: '1:358242017074:ios:03622a3cd83b459730012b',
    messagingSenderId: '358242017074',
    projectId: 'you-can-cook-1b811',
    databaseURL: 'https://you-can-cook-1b811-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'you-can-cook-1b811.firebasestorage.app',
    iosBundleId: 'com.example.youCanCook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDECLt-pA1IfCfoNi_jCfjNBP_-8ru0fHQ',
    appId: '1:358242017074:ios:03622a3cd83b459730012b',
    messagingSenderId: '358242017074',
    projectId: 'you-can-cook-1b811',
    databaseURL: 'https://you-can-cook-1b811-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'you-can-cook-1b811.firebasestorage.app',
    iosBundleId: 'com.example.youCanCook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIeIe8RtQPUedJKcMWqdFAhjI1Vcz_KKM',
    appId: '1:358242017074:web:c7d689067437d7d030012b',
    messagingSenderId: '358242017074',
    projectId: 'you-can-cook-1b811',
    authDomain: 'you-can-cook-1b811.firebaseapp.com',
    databaseURL: 'https://you-can-cook-1b811-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'you-can-cook-1b811.firebasestorage.app',
    measurementId: 'G-M81KGKHCS3',
  );
}
